[WIP] globale opzet gh-pages via eleventy
WCAG-Audit-Discussions/NL-BE pull request #4
Opened 2021-12-24 19:16 UTC by rianrietveld

Nog niet af, work in progress, gesubmit om alvast een structuur te bewaren.

2022-01-06 15:55 UTC, Aircl0wn commented on src/_includes/discussions.njk
> +{%- endfor -%}
Place if statement inside <ul>

```suggestion
<ul>
  {%- for discussie in collections[ number ] -%}
    <li><a href="#{{ discussie.data.title | slugify | url }}" hreflang="en">{{ discussie.data.title }}</a></li>
  {%- endfor -%}
</ul>
```

2022-01-07 12:12 UTC, rianrietveld commented
Hey @Aircl0wn , tnx voor de catch, maar ik ben nog aan het bouwen, dit hoeft nog geen code review nu :-)
Ik heb het gepusht om het te bewaren.
Zodat er echt wat staat geeft ik een gil

2022-01-07 12:59 UTC, Aircl0wn commented
haha sorry!, ik zat gewoon  te neuzen. Aard van het beestje.

2022-01-19 14:56 UTC, hidde commented on README.md
> +- [Ronny Hendirks](https://github.com/Aircl0wn) van Toegankelijk Online
typo 'Hendirks'

2022-01-19 14:57 UTC, hidde commented on README.md
> +
misschien hier nieuwe heading starten voor 
“Lokale installatie”? wantv anaf hier gaat het niet meer over GitHub Pages

2022-01-19 15:01 UTC, hidde requested changes

2022-01-19 15:01 UTC, hidde commented on src/sc/sc020202.njk
> +permalink: sc/{{ number }}.html
(dit comment geldt voor alle SCs)

2022-01-19 16:12 UTC, merged